package main.java.me.avankziar.mim.general;

public class StaticValues
{
	public static final String
		//CommandToBungee
		CMDTB_TOBUNGEE = "mim:cmdtb_tobungee", //Channel müssen kleingeschrieben werden!
		CMDTB_ASCONSOLE = "CMDTB_ASCONSOLE",
		CMDTB_ASCONSOLE_FORALLPLAYERS = "CMDTB_ASCONSOLE_FORALLPLAYERS",
		CMDTB_ASCONSOLE_FORALLPLAYERSREPLACER = "CMDTB_ASCONSOLE_FORALLPLAYERSREPLACER",
		CMDTB_ASPLAYER = "CMDTB_ASPLAYER",
		CMDTB_ASPLAYER_FORALLPLAYERS = "CMDTB_ASPLAYER_FORALLPLAYERS",
		CMDTB_ASPLAYER_FORALLPLAYERSREPLACER = "CMDTB_ASPLAYER_FORALLPLAYERSREPLACER",
		//PlayerParameter
		PP_TOBUNGEE = "mim:pp_tobungee",
		PP_TOSPIGOT = "mim:pp_tospigot",
		PP_SAVEALL = "PP_SAVEALL",
		PP_SAVESERVER = "PP_SAVEALL",
		PP_SAVEANDKICKALL = "PP_SAVESERVER",
		PP_SAVEANDKICKSERVER = "PP_SAVEANDKICKSERVER",
		//WhoIs
		WHOIS_TOBUNGEE = "mim:whois_tobungee",
		WHOIS_TOSPIGOT = "mim:whois_tospigot",
		WHOIS_SENDREQUEST = "WHOIS_SENDREQUEST",
		WHOIS_ANSWEROFFLINE = "WHOIS_ANSWEROFFLINE",
		WHOIS_ANSWERONLINE = "WHOIS_ANSWERONLINE",
		
		ONLINE_TOBUNGEE = "mim:online_tobungee",
		ONLINE_TOSPIGOT = "mim:online_tospigot",
		ONLINE_REQUEST = "ONLINE_REQUEST";
}