package main.java.me.avankziar.mim.general;

public class StaticValues
{
	public static final String
		//CommandToBungee
		CMDTB_TOBUNGEE = "CMDTB_TOBUNGEE",
		CMDTB_ASCONSOLE = "CMDTB_ASCONSOLE",
		CMDTB_ASCONSOLE_FORALLPLAYERS = "CMDTB_ASCONSOLE_FORALLPLAYERS",
		CMDTB_ASCONSOLE_FORALLPLAYERSREPLACER = "CMDTB_ASCONSOLE_FORALLPLAYERSREPLACER",
		CMDTB_ASPLAYER = "CMDTB_ASPLAYER",
		CMDTB_ASPLAYER_FORALLPLAYERS = "CMDTB_ASPLAYER_FORALLPLAYERS",
		CMDTB_ASPLAYER_FORALLPLAYERSREPLACER = "CMDTB_ASPLAYER_FORALLPLAYERSREPLACER",
		//PlayerParameter
		PP_TOBUNGEE = "PP_TOBUNGEE",
		PP_TOSPIGOT = "PP_TOSPIGOT",
		PP_SAVEALL = "PP_SAVEALL",
		PP_SAVESERVER = "PP_SAVEALL",
		PP_SAVEANDKICKALL = "PP_SAVESERVER",
		PP_SAVEANDKICKSERVER = "PP_SAVEANDKICKSERVER",
		//WhoIs
		WHOIS_TOBUNGEE = "WHOIS_TOBUNGEE",
		WHOIS_TOSPIGOT = "WHOIS_TOSPIGOT",
		WHOIS_SENDREQUEST = "WHOIS_SENDREQUEST",
		WHOIS_ANSWEROFFLINE = "WHOIS_ANSWEROFFLINE",
		WHOIS_ANSWERONLINE = "WHOIS_ANSWERONLINE";
}